### PR TITLE
Added Beginners section to README

### PR DESCRIPTION
**Pull request by olekscode**

### CODE REVIEW

**Comment by olekscode** [comment]
I will do i

**Comment by olekscode** [comment]
@jecisc I think that structure should not be hardcoded anywhere in Contribution guidelines. Because it can change and we will always forget to update it

**Comment by jecisc** [comment]
Currently, it is described in the Manifest to let users know without ambiguity the goal of each section.

**Comment by olekscode** [comment]
@jecisc check this one

**Comment by jecisc** [comment]
@juliendelplanque Ok for you?

**Pull request merged**
