### PR TITLE
Add script to rename methods programatically

### LINKED ISSUE #127: Add a script to rename programatically methods
I did a script with Benoit to rename a lot of methods of one of its visitors. I'll post it in cool snippets.

### PR DESCRIPTION
**Pull request by jecisc**
Fixes #127

### CODE REVIEW

**Comment by jecisc** [comment]
I wrote `all the methods of a class`.

Maybe later we can add alternatives to the snippet but the main goal was to expose how to programmatically do a rename.

**Comment by juliendelplanque** [comment]
So it does not modifies the source code of methods calling the renamed method?

**Comment by jecisc** [comment]
Yes, it does. It uses the rename method refactoring.

**Comment by jecisc** [comment]
I added a note

**Comment by juliendelplanque** [comment]
Nice, I merge it.

**Pull request merged**
