### PR TITLE
Minor spelling and grammar correction for beginner section

### PR DESCRIPTION
**Pull request by nikosk84**
I have corrected various spelling mistakes and minor grammar mistakes for the Beginner section of the documentation.

Please note, that the below description regarding the Receiver in the Glossary section, is very confusing for a beginner and I recommend the explanation be simplified. I read the sentence a couple of times but still didn't understand it in order to propose a correction.

_"**Receiver**
The receiver of a message send is the instance of a class implementing the method corresponding to the message sent receiving this message._"

### CODE REVIEW

**Review by juliendelplanque — APPROVED** [review]
Thanks a lot for taking your time to review the wiki. Most of us are not english native so it is hard to write correctly for us. :-)

Thanks a lot again!

**Comment by nikosk84** [comment]
> 
> 
> Thanks a lot for taking your time to review the wiki. Most of us are not english native so it is hard to write correctly for us. :-)
> 
> Thanks a lot again!

No problem! Happy to contribute!

**Comment by juliendelplanque** [comment]
> Please note, that the below description regarding the Receiver in the Glossary section, is very confusing for a beginner and I recommend the explanation be simplified. I read the sentence a couple of times but still didn't understand it in order to propose a correction.
> 
> _"**Receiver** The receiver of a message send is the instance of a class implementing the method corresponding to the message sent receiving this message._"

Maybe you can open a specific issue for this. This is actually complex to explain without an example.

**Comment by nikosk84** [comment]
> 
> 
> > Please note, that the below description regarding the Receiver in the Glossary section, is very confusing for a beginner and I recommend the explanation be simplified. I read the sentence a couple of times but still didn't understand it in order to propose a correction.
> > _"**Receiver** The receiver of a message send is the instance of a class implementing the method corresponding to the message sent receiving this message._"
> 
> Maybe you can open a specific issue for this. This is actually complex to explain without an example.

Absolutely, of course. Issue opened #316

**Pull request merged**
