### PR TITLE
Did a pass.

### PR DESCRIPTION
**Pull request by juliendelplanque**
I am not sure of what the quoted text at the beginning tries to explain.

Maybe you can develop @jecisc ?

### CODE REVIEW

**Comment by jecisc** [comment]
I wanted to say that we should not use DynamicVariables that are some kind of global variables for everything and that we should carefully consider if we use them or not. 

But I don't know well how to express the cases it should not be used.

**Comment by juliendelplanque** [comment]
We should try to explicit the cases where it is kind of an anti-pattern, to make it clear. Don't you think?

**Comment by jecisc** [comment]
Yes

**Comment by juliendelplanque** [comment]
I will merge this change as is for now else it will never be done :-) . We will fix it later if needed.

**Comment by jecisc** [comment]
+1

**Pull request merged**
