### PR TITLE
Created a master TableOfContent

### PR DESCRIPTION
**Pull request by NicolasAnquetil**
All first and 2nd level titles gathered in a big TABLEOFCONTENT file
+ a shell script to regenerate this

### CODE REVIEW

**Comment by juliendelplanque** [comment]
Although it seems to be well generated, I do not get why it is needed?
To search more easily through the entire wiki or something?

**Comment by jecisc** [comment]
If the goal is to make the search easier I'm not against it but we need an automatic way to regenerate it because it's a bother if we need to launch the script at each change in pages.

**Comment by juliendelplanque** [comment]
Yeah, maybe we can let a CI do it?

**Comment by juliendelplanque** [comment]
I close this PR since there is no more activity on it.
Do not hesitate to reopen if needed.

**Pull request closed without merging**
