### PR TITLE
First version of Numbers page, work in progress...

### PR DESCRIPTION
**Pull request by juliendelplanque**

### CODE REVIEW

**Comment by jecisc** [comment]
Is it "Work in progress" as "We can integrate with a In-progress tag or as "Do not merge this PR yet I'll add more content really soon"?

**Comment by juliendelplanque** [comment]
The second one!

**Comment by jecisc** [comment]
@juliendelplanque ping

**Comment by juliendelplanque** [comment]
I think I will merge it as is so people can look at what is already there and eventually contribute.
Else the PR will hang here forever.

**Pull request merged**
