### PR TITLE
Create page with vocabulary specific to Pharo

### PR DESCRIPTION
**Pull request by juliendelplanque**
This is in progress, what do you think about it @jecisc and @olekscode ?

### CODE REVIEW

**Comment by juliendelplanque** [comment]
Yeah and, add your ideas.

**Comment by jecisc** [comment]
Maybe the name should be « glossary »?
Also it should be added to the README with an in progress badge.

**Comment by juliendelplanque** [comment]
> Maybe the name should be « glossary »?

Maybe, I don't know

> Also it should be added to the README with an in progress badge.

Sure, and I think it should be in beginners section.

**Comment by jecisc** [comment]
Ideas: 
- Late binding
- dispatch
- pragma
- class side

Not sur for the first 2 since it’s not only related to Pharo

**Comment by Larcheveque** [comment]
Senders
Implementors
Receivers
Candidates

**Comment by Larcheveque** [comment]
Self
Super
Primitive
inspector
debugger

**Comment by jecisc** [comment]
- Context
- Object
- Instance
- Smalltalk
- Squeak
- Browser
- Iceberg
- Monticello

**Comment by jecisc** [comment]
Design pattern

**Comment by juliendelplanque** [comment]
I will try to fill them all but for the next propositions open issues else this page will never be published.

**Pull request merged**
