### PR TITLE
Update deployement

### PR DESCRIPTION
**Pull request by VincentBlondeau**
#153

### CODE REVIEW

**Comment by jecisc** [comment]
Should I wait before reviewing changes?

**Comment by VincentBlondeau** [comment]
Yes. That is what is progress means :)

**Comment by juliendelplanque** [comment]
I think we should merge as is. Else the PR will be hanging here forever. :-)

**Comment by juliendelplanque** [comment]
What do you think @VincentBlondeau ?

**Comment by VincentBlondeau** [comment]
You can merge as is but don't close the related issue

**Comment by juliendelplanque** [comment]
Yeah sure.

**Pull request merged**
